area/frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'
          - 'public/**'
          - '**/*.jsx'
          - '**/*.tsx'
          - 'vite.config.*'
          - 'tailwind.config.*'
          - 'postcss.config.*'

area/backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'backend/**'

area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'
          - 'README.md'

area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '.lychee.toml'
          - '.typos.toml'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'
          - 'pnpm-lock.yaml'
