name: DCO

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: read
  statuses: write

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commit sign-offs
        run: |
          echo "Checking for DCO sign-offs..."
          MISSING=0
          BASE_REF="${{ github.event.pull_request.base.ref }}"
          git fetch origin $BASE_REF
          COMMITS=$(git rev-list origin/$BASE_REF..HEAD)
          for COMMIT in $COMMITS; do
            if ! git log -1 --pretty=%B $COMMIT | grep -q "^Signed-off-by:"; then
              echo "::error file=commit::$COMMIT is missing a 'Signed-off-by:' line"
              MISSING=1
            fi
          done
          if [ "$MISSING" -ne 0 ]; then
            echo "❌ DCO check failed."
            exit 1
          else
            echo "✅ All commits are signed off."
          fi
