name: Link check

on:
  pull_request:
    paths:
      - '**/*.md'
      - 'docs/**'
      - 'public/**'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config .lychee.toml .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
