name: PR helper comment

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = [
              `Thanks for the PR, @${pr.user.login}!`,
              "",
              "**Quick note:** please **sign off** your commits to pass the DCO check.",
              "",
              "Fix (any one):",
              "```bash",
              "git commit --amend -s     # adds 'Signed-off-by' to your last commit",
              "git push --force-with-lease",
              "```",
              "Multiple commits?",
              "```bash",
              "git rebase -i origin/main     # mark each as 'reword' and add -s",
              "git push --force-with-lease",
              "```",
              "",
              "What is DCO? See https://developercertificate.org/"
            ].join("\n");
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body
            });
